import 'package:flutter/material.dart';
import 'package:formunda/formunda.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      home: CamundaFormPage(),
    );
  }
}

final Map<String, dynamic> rawData = {
  "executionPlatform": "Camunda Cloud",
  "executionPlatformVersion": "8.4.0",
  "exporter": {"name": "Camunda Web Modeler", "version": "e576085"},
  "schemaVersion": 19,
  "id": "checklist-rigging-alat-berat",
  "components": [
    {
      "label": "",
      "components": [
        {
          "type": "image",
          "layout": {"row": "Row_0xz33u4", "columns": null},
          "id": "Field_08z1llq",
          "source":
              "https://drive.google.com/thumbnail?id=1RSV2q3elh93UZpJT7DbKxUKQzcuYAe5v&sz=w1000",
        },
      ],
      "showOutline": true,
      "type": "group",
      "layout": {"row": "Row_1nejpso", "columns": 9},
      "id": "Field_03iehak",
    },
    {
      "label": "",
      "components": [
        {
          "label": "Document Number :",
          "type": "textfield",
          "layout": {"row": "Row_1lcxobz", "columns": null},
          "id": "Field_1glj2mu",
          "key": "textfield_o1n51",
          "defaultValue": "FR.PDT.OPR.001",
        },
        {
          "label": "Revision :",
          "type": "textfield",
          "layout": {"row": "Row_044b750", "columns": 5},
          "id": "Field_1ehr4cl",
          "key": "textfield_cn3h1dj",
          "defaultValue": "00",
        },
        {
          "subtype": "date",
          "dateLabel": "Issue Date :",
          "type": "datetime",
          "layout": {"row": "Row_044b750", "columns": null},
          "id": "Field_0nlt8zs",
          "key": "datetime_zy2wja",
        },
      ],
      "showOutline": true,
      "type": "group",
      "layout": {"row": "Row_1nejpso", "columns": null},
      "id": "Field_1em2prt",
    },
    {
      "text": "# PRE-CHECK TOOLS",
      "type": "text",
      "id": "title_main",
      "layout": {"row": "Row_14zsnyd"},
    },
    {
      "label": "DATA PEKERJAAN",
      "components": [
        {
          "label": "No. Dokumen",
          "type": "textfield",
          "id": "field_nomorDokumen",
          "key": "nomorDokumen",
          "validate": {"required": true},
          "layout": {"row": "Row_09nvckv"},
        },
        {
          "subtype": "date",
          "type": "datetime",
          "id": "field_tanggal",
          "key": "tanggal",
          "label": "Tanggal",
          "validate": {"required": true},
          "layout": {"row": "Row_0dao5rb"},
        },
        {
          "label": "Proyek / Job",
          "type": "textfield",
          "id": "field_proyekJob",
          "key": "proyekJob",
          "validate": {"required": true},
          "layout": {"row": "Row_0c55dz9"},
        },
        {
          "label": "Lokasi Loading",
          "type": "textfield",
          "id": "field_lokasiLoading",
          "key": "lokasiLoading",
          "validate": {"required": true},
          "layout": {"row": "Row_0it7gyu"},
        },
        {
          "label": "Alat Berat",
          "type": "textfield",
          "id": "field_alatBerat",
          "key": "alatBerat",
          "validate": {"required": true},
          "layout": {"row": "Row_05naohr"},
        },
        {
          "label": "Berat (ton)",
          "type": "number",
          "id": "field_beratTon",
          "key": "beratTon",
          "validate": {"required": true},
          "layout": {"row": "Row_07eq2nb"},
        },
        {
          "label": "Trailer Type",
          "type": "textfield",
          "id": "field_trailerType",
          "key": "trailerType",
          "validate": {"required": true},
          "layout": {"row": "Row_1cqs8ji"},
        },
        {
          "label": "Inspector",
          "type": "textfield",
          "id": "field_inspector",
          "key": "inspector",
          "validate": {"required": true},
          "layout": {"row": "Row_1yd1vog"},
        },
        {
          "label": "Shift / Waktu",
          "type": "textfield",
          "id": "field_shiftWaktu",
          "key": "shiftWaktu",
          "validate": {"required": true},
          "layout": {"row": "Row_01l5fkg"},
        },
        {
          "label": "Supervisor",
          "type": "textfield",
          "id": "field_supervisor",
          "key": "supervisor",
          "validate": {"required": true},
          "layout": {"row": "Row_1hyne1j"},
        },
      ],
      "showOutline": true,
      "type": "group",
      "id": "group_data_pekerjaan",
      "layout": {"row": "Row_1v9wwmg"},
    },
    {
      "label": "A. WIRE ROPE SLING",
      "components": [
        {
          "label": "1. Tipe konstruksi wire rope (6x19 / 6x37 / IWRC)",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_a01",
          "key": "a01_konstruksi",
          "validate": {"required": true},
          "layout": {"row": "Row_0qt4o07"},
        },
        {
          "label": "Catatan item 1",
          "type": "textarea",
          "id": "field_cat_a01",
          "key": "catatan_a01",
          "layout": {"row": "Row_08tshw9"},
        },
        {
          "label": "2. Diameter wire rope",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_a02",
          "key": "a02_diameter",
          "validate": {"required": true},
          "layout": {"row": "Row_08veeft"},
        },
        {
          "label": "Catatan item 2",
          "type": "textarea",
          "id": "field_cat_a02",
          "key": "catatan_a02",
          "layout": {"row": "Row_1egiwc0"},
        },
        {
          "label": "3. Panjang sling",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_a03",
          "key": "a03_panjang",
          "validate": {"required": true},
          "layout": {"row": "Row_0fvchnd"},
        },
        {
          "label": "Catatan item 3",
          "type": "textarea",
          "id": "field_cat_a03",
          "key": "catatan_a03",
          "layout": {"row": "Row_02q6pqn"},
        },
        {
          "label": "4. Tidak ada kinking / kinking permanen",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_a04",
          "key": "a04_kinking",
          "validate": {"required": true},
          "layout": {"row": "Row_1j0vjgp"},
        },
        {
          "label": "Catatan item 4",
          "type": "textarea",
          "id": "field_cat_a04",
          "key": "catatan_a04",
          "layout": {"row": "Row_1tz1lz6"},
        },
        {
          "label": "5. Tidak ada bird caging / unlaying",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_a05",
          "key": "a05_birdcaging",
          "validate": {"required": true},
          "layout": {"row": "Row_0lka2de"},
        },
        {
          "label": "Catatan item 5",
          "type": "textarea",
          "id": "field_cat_a05",
          "key": "catatan_a05",
          "layout": {"row": "Row_0s49e0z"},
        },
        {
          "label": "6. Tidak ada broken wires >10% per lay length",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_a06",
          "key": "a06_brokenWires",
          "validate": {"required": true},
          "layout": {"row": "Row_1nius93"},
        },
        {
          "label": "Catatan item 6",
          "type": "textarea",
          "id": "field_cat_a06",
          "key": "catatan_a06",
          "layout": {"row": "Row_03hi188"},
        },
        {
          "label": "7. Tidak ada karat berat / korosi",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_a07",
          "key": "a07_karat",
          "validate": {"required": true},
          "layout": {"row": "Row_0j4gy8s"},
        },
        {
          "label": "Catatan item 7",
          "type": "textarea",
          "id": "field_cat_a07",
          "key": "catatan_a07",
          "layout": {"row": "Row_1njq20v"},
        },
        {
          "label": "8. Tidak ada crush / flat spot",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_a08",
          "key": "a08_crush",
          "validate": {"required": true},
          "layout": {"row": "Row_1f504tw"},
        },
        {
          "label": "Catatan item 8",
          "type": "textarea",
          "id": "field_cat_a08",
          "key": "catatan_a08",
          "layout": {"row": "Row_1c9rryt"},
        },
        {
          "label": "9. Thimble / eye fitting kondisi baik (tidak pecah/cacat)",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_a09",
          "key": "a09_thimble",
          "validate": {"required": true},
          "layout": {"row": "Row_0dfr0oq"},
        },
        {
          "label": "Catatan item 9",
          "type": "textarea",
          "id": "field_cat_a09",
          "key": "catatan_a09",
          "layout": {"row": "Row_0oifphp"},
        },
        {
          "label": "10. Tag/label SWL terpasang & terbaca",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_a10",
          "key": "a10_tagSWL",
          "validate": {"required": true},
          "layout": {"row": "Row_1bsqmao"},
        },
        {
          "label": "Catatan item 10",
          "type": "textarea",
          "id": "field_cat_a10",
          "key": "catatan_a10",
          "layout": {"row": "Row_046syew"},
        },
        {
          "label": "11. Sertifikat inspeksi masih berlaku (maks. 12 bulan)",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_a11",
          "key": "a11_sertifikat",
          "validate": {"required": true},
          "layout": {"row": "Row_0rnoaf8"},
        },
        {
          "label": "Catatan item 11",
          "type": "textarea",
          "id": "field_cat_a11",
          "key": "catatan_a11",
          "layout": {"row": "Row_0zbqg48"},
        },
      ],
      "showOutline": true,
      "type": "group",
      "id": "group_section_a",
      "layout": {"row": "Row_0koktyh"},
    },
    {
      "label": "B. CHAIN SLING",
      "components": [
        {
          "label": "12. Grade rantai (Grade 80 / Grade 100)",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_b12",
          "key": "b12_grade",
          "validate": {"required": true},
          "layout": {"row": "Row_165ooyd"},
        },
        {
          "label": "Catatan item 12",
          "type": "textarea",
          "id": "field_cat_b12",
          "key": "catatan_b12",
          "layout": {"row": "Row_1w9nhp2"},
        },
        {
          "label": "13. Tidak ada mata rantai yang retak / patah",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_b13",
          "key": "b13_retakPatah",
          "validate": {"required": true},
          "layout": {"row": "Row_0yat7yj"},
        },
        {
          "label": "Catatan item 13",
          "type": "textarea",
          "id": "field_cat_b13",
          "key": "catatan_b13",
          "layout": {"row": "Row_0ddkwxh"},
        },
        {
          "label": "14. Tidak ada deformasi / elongasi pada mata rantai",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_b14",
          "key": "b14_deformasi",
          "validate": {"required": true},
          "layout": {"row": "Row_1cuw1l8"},
        },
        {
          "label": "Catatan item 14",
          "type": "textarea",
          "id": "field_cat_b14",
          "key": "catatan_b14",
          "layout": {"row": "Row_0zxrmz0"},
        },
        {
          "label": "15. Tidak ada keausan berlebihan pada mata rantai",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_b15",
          "key": "b15_keausan",
          "validate": {"required": true},
          "layout": {"row": "Row_0fyfwt1"},
        },
        {
          "label": "Catatan item 15",
          "type": "textarea",
          "id": "field_cat_b15",
          "key": "catatan_b15",
          "layout": {"row": "Row_1gkrq4x"},
        },
        {
          "label": "16. Master link / master coupling kondisi baik",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_b16",
          "key": "b16_masterLink",
          "validate": {"required": true},
          "layout": {"row": "Row_1q833wa"},
        },
        {
          "label": "Catatan item 16",
          "type": "textarea",
          "id": "field_cat_b16",
          "key": "catatan_b16",
          "layout": {"row": "Row_0oyaek4"},
        },
        {
          "label": "17. Hook di ujung rantai – latch berfungsi normal",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_b17",
          "key": "b17_hookLatch",
          "validate": {"required": true},
          "layout": {"row": "Row_0g4wq9w"},
        },
        {
          "label": "Catatan item 17",
          "type": "textarea",
          "id": "field_cat_b17",
          "key": "catatan_b17",
          "layout": {"row": "Row_0nrq7el"},
        },
        {
          "label": "18. Tag SWL terpasang dan terbaca",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_b18",
          "key": "b18_tagSWL",
          "validate": {"required": true},
          "layout": {"row": "Row_1rj2yx1"},
        },
        {
          "label": "Catatan item 18",
          "type": "textarea",
          "id": "field_cat_b18",
          "key": "catatan_b18",
          "layout": {"row": "Row_1omb7ef"},
        },
        {
          "label": "19. Sertifikat inspeksi masih berlaku",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_b19",
          "key": "b19_sertifikat",
          "validate": {"required": true},
          "layout": {"row": "Row_159pt7h"},
        },
        {
          "label": "Catatan item 19",
          "type": "textarea",
          "id": "field_cat_b19",
          "key": "catatan_b19",
          "layout": {"row": "Row_094oc3w"},
        },
      ],
      "showOutline": true,
      "type": "group",
      "id": "group_section_b",
      "layout": {"row": "Row_0u9i1v6"},
    },
    {
      "label": "C. WEBBING SLING (TEXTILE SLING)",
      "components": [
        {
          "label": "20. Material webbing – polyester (bukan nylon untuk asam)",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_c20",
          "key": "c20_material",
          "validate": {"required": true},
          "layout": {"row": "Row_1wgn225"},
        },
        {
          "label": "Catatan item 20",
          "type": "textarea",
          "id": "field_cat_c20",
          "key": "catatan_c20",
          "layout": {"row": "Row_084uwwr"},
        },
        {
          "label": "21. Tidak ada sobekan / potongan pada badan sling",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_c21",
          "key": "c21_sobekan",
          "validate": {"required": true},
          "layout": {"row": "Row_18o32mj"},
        },
        {
          "label": "Catatan item 21",
          "type": "textarea",
          "id": "field_cat_c21",
          "key": "catatan_c21",
          "layout": {"row": "Row_0f4uttm"},
        },
        {
          "label": "22. Tidak ada tanda bakar / heat damage pada material",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_c22",
          "key": "c22_heatDamage",
          "validate": {"required": true},
          "layout": {"row": "Row_19ow3gx"},
        },
        {
          "label": "Catatan item 22",
          "type": "textarea",
          "id": "field_cat_c22",
          "key": "catatan_c22",
          "layout": {"row": "Row_1vdelxg"},
        },
        {
          "label": "23. Tidak ada kontaminasi kimia / minyak berlebihan",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_c23",
          "key": "c23_kontaminasi",
          "validate": {"required": true},
          "layout": {"row": "Row_0w83eop"},
        },
        {
          "label": "Catatan item 23",
          "type": "textarea",
          "id": "field_cat_c23",
          "key": "catatan_c23",
          "layout": {"row": "Row_0h0cfst"},
        },
        {
          "label": "24. Jahitan ujung (loop) – tidak ada jahitan terlepas",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_c24",
          "key": "c24_jahitan",
          "validate": {"required": true},
          "layout": {"row": "Row_0ea5raz"},
        },
        {
          "label": "Catatan item 24",
          "type": "textarea",
          "id": "field_cat_c24",
          "key": "catatan_c24",
          "layout": {"row": "Row_0e7gx59"},
        },
        {
          "label": "25. Tidak ada abrasi berat (>10% material tergerus)",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_c25",
          "key": "c25_abrasi",
          "validate": {"required": true},
          "layout": {"row": "Row_0fhi8h7"},
        },
        {
          "label": "Catatan item 25",
          "type": "textarea",
          "id": "field_cat_c25",
          "key": "catatan_c25",
          "layout": {"row": "Row_12ptcrg"},
        },
        {
          "label": "26. Tag SWL terpasang dan terbaca",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_c26",
          "key": "c26_tagSWL",
          "validate": {"required": true},
          "layout": {"row": "Row_04w33tw"},
        },
        {
          "label": "Catatan item 26",
          "type": "textarea",
          "id": "field_cat_c26",
          "key": "catatan_c26",
          "layout": {"row": "Row_0ap7ryz"},
        },
        {
          "label": "27. Sertifikat inspeksi masih berlaku",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_c27",
          "key": "c27_sertifikat",
          "validate": {"required": true},
          "layout": {"row": "Row_1c5yvrc"},
        },
        {
          "label": "Catatan item 27",
          "type": "textarea",
          "id": "field_cat_c27",
          "key": "catatan_c27",
          "layout": {"row": "Row_1tat45b"},
        },
      ],
      "showOutline": true,
      "type": "group",
      "id": "group_section_c",
      "layout": {"row": "Row_16hskg8"},
    },
    {
      "label": "D. SHACKLE (BOW / DEE)",
      "components": [
        {
          "label": "28. Tipe shackle sesuai konfigurasi (bow / dee)",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_d28",
          "key": "d28_tipe",
          "validate": {"required": true},
          "layout": {"row": "Row_1bjtoo5"},
        },
        {
          "label": "Catatan item 28",
          "type": "textarea",
          "id": "field_cat_d28",
          "key": "catatan_d28",
          "layout": {"row": "Row_1pr7fdo"},
        },
        {
          "label": "29. Rating / WLL sesuai atau melebihi beban kerja",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_d29",
          "key": "d29_ratingWLL",
          "validate": {"required": true},
          "layout": {"row": "Row_0d4gl20"},
        },
        {
          "label": "Catatan item 29",
          "type": "textarea",
          "id": "field_cat_d29",
          "key": "catatan_d29",
          "layout": {"row": "Row_0uukuot"},
        },
        {
          "label":
              "30. Bodi shackle – tidak ada retak, nick, atau grooves dalam",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_d30",
          "key": "d30_bodi",
          "validate": {"required": true},
          "layout": {"row": "Row_1wk05yj"},
        },
        {
          "label": "Catatan item 30",
          "type": "textarea",
          "id": "field_cat_d30",
          "key": "catatan_d30",
          "layout": {"row": "Row_13tmv7h"},
        },
        {
          "label": "31. Pin / bolt kondisi baik – tidak bengkok, tidak aus",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_d31",
          "key": "d31_pin",
          "validate": {"required": true},
          "layout": {"row": "Row_1sy254u"},
        },
        {
          "label": "Catatan item 31",
          "type": "textarea",
          "id": "field_cat_d31",
          "key": "catatan_d31",
          "layout": {"row": "Row_18tn6fy"},
        },
        {
          "label": "32. Cotter pin / mousing wire terpasang di semua shackle",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_d32",
          "key": "d32_cotterPin",
          "validate": {"required": true},
          "layout": {"row": "Row_1wn130c"},
        },
        {
          "label": "Catatan item 32",
          "type": "textarea",
          "id": "field_cat_d32",
          "key": "catatan_d32",
          "layout": {"row": "Row_0u6bijj"},
        },
        {
          "label": "33. Pin terpasang sepenuhnya (sampai bahu pin)",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_d33",
          "key": "d33_pinTerpasang",
          "validate": {"required": true},
          "layout": {"row": "Row_1ao6fd3"},
        },
        {
          "label": "Catatan item 33",
          "type": "textarea",
          "id": "field_cat_d33",
          "key": "catatan_d33",
          "layout": {"row": "Row_1axnqao"},
        },
        {
          "label": "34. Marking SWL terpasang dan terbaca di bodi",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_d34",
          "key": "d34_markingSWL",
          "validate": {"required": true},
          "layout": {"row": "Row_1cbjwxg"},
        },
        {
          "label": "Catatan item 34",
          "type": "textarea",
          "id": "field_cat_d34",
          "key": "catatan_d34",
          "layout": {"row": "Row_1trr4j6"},
        },
      ],
      "showOutline": true,
      "type": "group",
      "id": "group_section_d",
      "layout": {"row": "Row_03iyvvh"},
    },
    {
      "label": "E. CHAIN BLOCK & LEVER HOIST",
      "components": [
        {
          "label": "35. Kapasitas chain block sesuai atau melebihi beban",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_e35",
          "key": "e35_kapasitas",
          "validate": {"required": true},
          "layout": {"row": "Row_091koha"},
        },
        {
          "label": "Catatan item 35",
          "type": "textarea",
          "id": "field_cat_e35",
          "key": "catatan_e35",
          "layout": {"row": "Row_08db09x"},
        },
        {
          "label": "36. Load chain – tidak ada kerusakan, tidak ada kink",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_e36",
          "key": "e36_loadChain",
          "validate": {"required": true},
          "layout": {"row": "Row_1yzkmub"},
        },
        {
          "label": "Catatan item 36",
          "type": "textarea",
          "id": "field_cat_e36",
          "key": "catatan_e36",
          "layout": {"row": "Row_1n2vzix"},
        },
        {
          "label": "37. Hand chain / lever – bergerak lancar tanpa macet",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_e37",
          "key": "e37_handChain",
          "validate": {"required": true},
          "layout": {"row": "Row_0peefw8"},
        },
        {
          "label": "Catatan item 37",
          "type": "textarea",
          "id": "field_cat_e37",
          "key": "catatan_e37",
          "layout": {"row": "Row_0aoqe61"},
        },
        {
          "label": "38. Hook atas – safety latch menutup sempurna",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_e38",
          "key": "e38_hookAtas",
          "validate": {"required": true},
          "layout": {"row": "Row_0xqupr7"},
        },
        {
          "label": "Catatan item 38",
          "type": "textarea",
          "id": "field_cat_e38",
          "key": "catatan_e38",
          "layout": {"row": "Row_13q1qn4"},
        },
        {
          "label": "39. Hook bawah (load hook) – safety latch menutup",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_e39",
          "key": "e39_hookBawah",
          "validate": {"required": true},
          "layout": {"row": "Row_0mxjzhn"},
        },
        {
          "label": "Catatan item 39",
          "type": "textarea",
          "id": "field_cat_e39",
          "key": "catatan_e39",
          "layout": {"row": "Row_1em2r7o"},
        },
        {
          "label":
              "40. Rem / brake berfungsi normal (tidak slip saat dibebani)",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_e40",
          "key": "e40_rem",
          "validate": {"required": true},
          "layout": {"row": "Row_1kh4n89"},
        },
        {
          "label": "Catatan item 40",
          "type": "textarea",
          "id": "field_cat_e40",
          "key": "catatan_e40",
          "layout": {"row": "Row_1hd9n91"},
        },
        {
          "label": "41. Rumah gearbox – tidak ada retakan atau kebocoran oli",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_e41",
          "key": "e41_gearbox",
          "validate": {"required": true},
          "layout": {"row": "Row_04frk8r"},
        },
        {
          "label": "Catatan item 41",
          "type": "textarea",
          "id": "field_cat_e41",
          "key": "catatan_e41",
          "layout": {"row": "Row_0bbxhu5"},
        },
        {
          "label": "42. Sertifikasi / load test masih berlaku",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_e42",
          "key": "e42_sertifikat",
          "validate": {"required": true},
          "layout": {"row": "Row_141peey"},
        },
        {
          "label": "Catatan item 42",
          "type": "textarea",
          "id": "field_cat_e42",
          "key": "catatan_e42",
          "layout": {"row": "Row_031mfnv"},
        },
      ],
      "showOutline": true,
      "type": "group",
      "id": "group_section_e",
      "layout": {"row": "Row_0d7h8gs"},
    },
    {
      "label": "F. CHAIN LASHING & RATCHET STRAPPING",
      "components": [
        {
          "label": "43. Jumlah chain lashing sesuai perhitungan (min. 4 titik)",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_f43",
          "key": "f43_jumlah",
          "validate": {"required": true},
          "layout": {"row": "Row_1yp494j"},
        },
        {
          "label": "Catatan item 43",
          "type": "textarea",
          "id": "field_cat_f43",
          "key": "catatan_f43",
          "layout": {"row": "Row_1uuvj91"},
        },
        {
          "label": "44. Grade & SWL chain lashing sesuai berat muatan",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_f44",
          "key": "f44_gradeSWL",
          "validate": {"required": true},
          "layout": {"row": "Row_1x4ohsf"},
        },
        {
          "label": "Catatan item 44",
          "type": "textarea",
          "id": "field_cat_f44",
          "key": "catatan_f44",
          "layout": {"row": "Row_0e4lyvj"},
        },
        {
          "label":
              "45. Kondisi fisik chain lashing – tidak ada retak / elongasi",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_f45",
          "key": "f45_kondisi",
          "validate": {"required": true},
          "layout": {"row": "Row_0ar0xp2"},
        },
        {
          "label": "Catatan item 45",
          "type": "textarea",
          "id": "field_cat_f45",
          "key": "catatan_f45",
          "layout": {"row": "Row_08q3t96"},
        },
        {
          "label": "46. Ratchet tensioner – bergerak halus, tidak slek",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_f46",
          "key": "f46_ratchet",
          "validate": {"required": true},
          "layout": {"row": "Row_10xymts"},
        },
        {
          "label": "Catatan item 46",
          "type": "textarea",
          "id": "field_cat_f46",
          "key": "catatan_f46",
          "layout": {"row": "Row_12zblnk"},
        },
        {
          "label": "47. Hook lashing – safety latch berfungsi",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_f47",
          "key": "f47_hookLashing",
          "validate": {"required": true},
          "layout": {"row": "Row_1be6q3h"},
        },
        {
          "label": "Catatan item 47",
          "type": "textarea",
          "id": "field_cat_f47",
          "key": "catatan_f47",
          "layout": {"row": "Row_06ty300"},
        },
        {
          "label":
              "48. Ratchet strapping – tidak ada sobekan / fraying pada webbing",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_f48",
          "key": "f48_strapping",
          "validate": {"required": true},
          "layout": {"row": "Row_0s1v6zk"},
        },
        {
          "label": "Catatan item 48",
          "type": "textarea",
          "id": "field_cat_f48",
          "key": "catatan_f48",
          "layout": {"row": "Row_09doz56"},
        },
        {
          "label":
              "49. Corner protector tersedia sesuai jumlah sudut tajam muatan",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_f49",
          "key": "f49_cornerProtector",
          "validate": {"required": true},
          "layout": {"row": "Row_0odvgk9"},
        },
        {
          "label": "Catatan item 49",
          "type": "textarea",
          "id": "field_cat_f49",
          "key": "catatan_f49",
          "layout": {"row": "Row_0btgggk"},
        },
      ],
      "showOutline": true,
      "type": "group",
      "id": "group_section_f",
      "layout": {"row": "Row_0muaz5j"},
    },
    {
      "label": "G. ALAT BANTU & AKSESORIS",
      "components": [
        {
          "label": "50. Timber block / hardwood – tidak busuk, tidak retak",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_g50",
          "key": "g50_timberBlock",
          "validate": {"required": true},
          "layout": {"row": "Row_1x9tbih"},
        },
        {
          "label": "Catatan item 50",
          "type": "textarea",
          "id": "field_cat_g50",
          "key": "catatan_g50",
          "layout": {"row": "Row_0z9vv8h"},
        },
        {
          "label": "51. Dunnage mat / rubber mat tersedia di bawah alat berat",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_g51",
          "key": "g51_dunmageMat",
          "validate": {"required": true},
          "layout": {"row": "Row_0588xvi"},
        },
        {
          "label": "Catatan item 51",
          "type": "textarea",
          "id": "field_cat_g51",
          "key": "catatan_g51",
          "layout": {"row": "Row_1jx3sy5"},
        },
        {
          "label": "52. Wheel chock (ganjal roda) tersedia – minimal 4 buah",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_g52",
          "key": "g52_wheelChock",
          "validate": {"required": true},
          "layout": {"row": "Row_0qu1216"},
        },
        {
          "label": "Catatan item 52",
          "type": "textarea",
          "id": "field_cat_g52",
          "key": "catatan_g52",
          "layout": {"row": "Row_0y94uyt"},
        },
        {
          "label": "53. Hydraulic jack – kondisi baik, tidak bocor",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_g53",
          "key": "g53_hydraulicJack",
          "validate": {"required": true},
          "layout": {"row": "Row_0bfz1sd"},
        },
        {
          "label": "Catatan item 53",
          "type": "textarea",
          "id": "field_cat_g53",
          "key": "catatan_g53",
          "layout": {"row": "Row_1pyuyo0"},
        },
        {
          "label": "54. Spreader bar – kondisi baik, sertifikat masih berlaku",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_g54",
          "key": "g54_spreaderBar",
          "validate": {"required": true},
          "layout": {"row": "Row_14mz76w"},
        },
        {
          "label": "Catatan item 54",
          "type": "textarea",
          "id": "field_cat_g54",
          "key": "catatan_g54",
          "layout": {"row": "Row_0dv11vi"},
        },
        {
          "label": "55. Loading ramp / bridging plate kondisi baik",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_g55",
          "key": "g55_loadingRamp",
          "validate": {"required": true},
          "layout": {"row": "Row_0u4dt6w"},
        },
        {
          "label": "Catatan item 55",
          "type": "textarea",
          "id": "field_cat_g55",
          "key": "catatan_g55",
          "layout": {"row": "Row_1dlwn7c"},
        },
        {
          "label":
              "56. Turnbuckle / load binder – ulir tidak rusak, bergerak lancar",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_g56",
          "key": "g56_turnbuckle",
          "validate": {"required": true},
          "layout": {"row": "Row_0z2gmog"},
        },
        {
          "label": "Catatan item 56",
          "type": "textarea",
          "id": "field_cat_g56",
          "key": "catatan_g56",
          "layout": {"row": "Row_0keoz90"},
        },
      ],
      "showOutline": true,
      "type": "group",
      "id": "group_section_g",
      "layout": {"row": "Row_19yoxow"},
    },
    {
      "label": "H. APD PERSONEL RIGGING",
      "components": [
        {
          "label": "57. Helm safety (hardhat) – semua personel",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_h57",
          "key": "h57_helm",
          "validate": {"required": true},
          "layout": {"row": "Row_0hid2tb"},
        },
        {
          "label": "Catatan item 57",
          "type": "textarea",
          "id": "field_cat_h57",
          "key": "catatan_h57",
          "layout": {"row": "Row_0nlo109"},
        },
        {
          "label": "58. Safety shoes / steel toe cap – semua personel",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_h58",
          "key": "h58_safetyShoes",
          "validate": {"required": true},
          "layout": {"row": "Row_0hutgxl"},
        },
        {
          "label": "Catatan item 58",
          "type": "textarea",
          "id": "field_cat_h58",
          "key": "catatan_h58",
          "layout": {"row": "Row_09h21gj"},
        },
        {
          "label": "59. Sarung tangan kulit / cut-resistant – rigger & helper",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_h59",
          "key": "h59_sarungTangan",
          "validate": {"required": true},
          "layout": {"row": "Row_1vjcn9g"},
        },
        {
          "label": "Catatan item 59",
          "type": "textarea",
          "id": "field_cat_h59",
          "key": "catatan_h59",
          "layout": {"row": "Row_0xppmt4"},
        },
        {
          "label": "60. Rompi / safety vest high-visibility",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_h60",
          "key": "h60_safetyVest",
          "validate": {"required": true},
          "layout": {"row": "Row_07ic2b8"},
        },
        {
          "label": "Catatan item 60",
          "type": "textarea",
          "id": "field_cat_h60",
          "key": "catatan_h60",
          "layout": {"row": "Row_1htqy00"},
        },
        {
          "label": "61. Safety harness (jika kerja di ketinggian >1.8m)",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_h61",
          "key": "h61_harness",
          "validate": {"required": true},
          "layout": {"row": "Row_1loxqf4"},
        },
        {
          "label": "Catatan item 61",
          "type": "textarea",
          "id": "field_cat_h61",
          "key": "catatan_h61",
          "layout": {"row": "Row_11id26e"},
        },
        {
          "label": "62. Kacamata safety / face shield jika diperlukan",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_h62",
          "key": "h62_kacamata",
          "validate": {"required": true},
          "layout": {"row": "Row_15pq0wa"},
        },
        {
          "label": "Catatan item 62",
          "type": "textarea",
          "id": "field_cat_h62",
          "key": "catatan_h62",
          "layout": {"row": "Row_16akp7f"},
        },
        {
          "label":
              "63. Radio / HT berfungsi – operator, rigger, spotter, supervisor",
          "values": [
            {"label": "OK – Kondisi Baik", "value": "OK"},
            {"label": "NG – Tidak Layak", "value": "NG"},
            {"label": "N/A – Tidak Berlaku", "value": "NA"},
          ],
          "type": "select",
          "id": "field_h63",
          "key": "h63_radioHT",
          "validate": {"required": true},
          "layout": {"row": "Row_1pxlvsb"},
        },
        {
          "label": "Catatan item 63",
          "type": "textarea",
          "id": "field_cat_h63",
          "key": "catatan_h63",
          "layout": {"row": "Row_0tbvj41"},
        },
      ],
      "showOutline": true,
      "type": "group",
      "id": "group_section_h",
      "layout": {"row": "Row_01scgqj"},
    },
    {
      "label": "TANDA TANGAN & PERSETUJUAN",
      "components": [
        {
          "label": "Dibuat oleh Rigger / Inspector",
          "type": "textfield",
          "id": "field_dibuatOleh",
          "key": "dibuatOleh",
          "validate": {"required": true},
          "layout": {"row": "Row_1fva3eq"},
        },
        {
          "label": "Diperiksa oleh Supervisor",
          "type": "textfield",
          "id": "field_diperiksaOleh",
          "key": "diperiksaOleh",
          "validate": {"required": true},
          "layout": {"row": "Row_1yb9o6j"},
        },
        {
          "label": "Disetujui oleh Site Manager",
          "type": "textfield",
          "id": "field_disetujuiOleh",
          "key": "disetujuiOleh",
          "validate": {"required": true},
          "layout": {"row": "Row_0wttykr"},
        },
        {
          "subtype": "datetime",
          "type": "datetime",
          "id": "field_tanggalMulai",
          "key": "tanggalMulai",
          "label": "Tanggal & Waktu Mulai Operasi",
          "validate": {"required": true},
          "layout": {"row": "Row_0lbxdq4"},
        },
      ],
      "showOutline": true,
      "type": "group",
      "id": "group_ttd",
      "layout": {"row": "Row_1i62pn7"},
    },
    {
      "text":
          "### ⚠ STOP WORK AUTHORITY\n**PERHATIAN: Terdapat item dengan status NG (Tidak Layak). Operasi loading HARUS DIHENTIKAN sampai semua item NG diperbaiki, diganti, dan diinspeksi ulang. Stop-work authority berlaku untuk semua personel.**",
      "type": "text",
      "id": "alert_stop_work",
      "condition": {
        "hide":
            "=(\"NG\" != a01_konstruksi) and (\"NG\" != a02_diameter) and (\"NG\" != a03_panjang) and (\"NG\" != a04_kinking) and (\"NG\" != a05_birdcaging) and (\"NG\" != a06_brokenWires) and (\"NG\" != a07_karat) and (\"NG\" != a08_crush) and (\"NG\" != a09_thimble) and (\"NG\" != a10_tagSWL) and (\"NG\" != a11_sertifikat) and (\"NG\" != b12_grade) and (\"NG\" != b13_retakPatah) and (\"NG\" != b14_deformasi) and (\"NG\" != b15_keausan) and (\"NG\" != b16_masterLink) and (\"NG\" != b17_hookLatch) and (\"NG\" != b18_tagSWL) and (\"NG\" != b19_sertifikat) and (\"NG\" != c20_material) and (\"NG\" != c21_sobekan) and (\"NG\" != c22_heatDamage) and (\"NG\" != c23_kontaminasi) and (\"NG\" != c24_jahitan) and (\"NG\" != c25_abrasi) and (\"NG\" != c26_tagSWL) and (\"NG\" != c27_sertifikat) and (\"NG\" != d28_tipe) and (\"NG\" != d29_ratingWLL) and (\"NG\" != d30_bodi) and (\"NG\" != d31_pin) and (\"NG\" != d32_cotterPin) and (\"NG\" != d33_pinTerpasang) and (\"NG\" != d34_markingSWL) and (\"NG\" != e35_kapasitas) and (\"NG\" != e36_loadChain) and (\"NG\" != e37_handChain) and (\"NG\" != e38_hookAtas) and (\"NG\" != e39_hookBawah) and (\"NG\" != e40_rem) and (\"NG\" != e41_gearbox) and (\"NG\" != e42_sertifikat) and (\"NG\" != f43_jumlah) and (\"NG\" != f44_gradeSWL) and (\"NG\" != f45_kondisi) and (\"NG\" != f46_ratchet) and (\"NG\" != f47_hookLashing) and (\"NG\" != f48_strapping) and (\"NG\" != f49_cornerProtector) and (\"NG\" != g50_timberBlock) and (\"NG\" != g51_dunmageMat) and (\"NG\" != g52_wheelChock) and (\"NG\" != g53_hydraulicJack) and (\"NG\" != g54_spreaderBar) and (\"NG\" != g55_loadingRamp) and (\"NG\" != g56_turnbuckle) and (\"NG\" != h57_helm) and (\"NG\" != h58_safetyShoes) and (\"NG\" != h59_sarungTangan) and (\"NG\" != h60_safetyVest) and (\"NG\" != h61_harness) and (\"NG\" != h62_kacamata) and (\"NG\" != h63_radioHT)",
      },
      "layout": {"row": "Row_14dvw3g"},
    },
  ],
  "type": "default",
};

class CamundaFormPage extends StatefulWidget {
  const CamundaFormPage({super.key});

  @override
  State<CamundaFormPage> createState() => _CamundaFormPageState();
}

class _CamundaFormPageState extends State<CamundaFormPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Formunda')),
     body: FormundaBuilder(json: rawData),
    );
  }
}
